version: '3'
services:
  proxy:
    hostname: proxy
    image: jwilder/nginx-proxy
    container_name: proxydaw
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy:/etc/nginx/vhost.d:ro
      - "./conf/my_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf:ro"
    networks:
      - frontend
  web1: #Sitio de ejemplo
    image: php:8.1-apache # basta un apache con php
    container_name: web1
    hostname: web1
    volumes:
      - ./sitios/web1:/var/www/html
    environment:
      - VIRTUAL_HOST=web1.com,www.web1.com
    restart: always
    networks:
      - frontend
      - backend
  dwes: #sitio con material del profesor
    build: ./dockerfiles/dwes
    container_name: dwes
    hostname: dwes
    volumes:
      - ./sitios/dwes:/var/www/html
    environment:
      - VIRTUAL_HOST=dwes.local
    restart: always
    networks:
      - frontend
      - backend
  mvc: #sitio con material del profesor
    build: ./dockerfiles/dwes
    container_name: mvc
    hostname: mvc
    volumes:
      - /home/alumno/dwes/UD4:/var/www/html
    environment:
      - VIRTUAL_HOST=mvc.local
    restart: always
    networks:
      - frontend
      - backend
  laravel:
    build:
      context: './dockerfiles/laravel'
      args:
        uid: 1000
    container_name: laravel
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - VIRTUAL_HOST=laravel.local
    volumes:
      - /home/alumno/dwes/UD5/clase00:/var/www/html
    networks:
      - frontend
      - backend
  chapp:
    build:
      context: './dockerfiles/laravel'
      args:
        uid: 1000
    container_name: chapp
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - VIRTUAL_HOST=chapp.local
    volumes:
      - /home/alumno/app:/var/www/html
    networks:
      - frontend
      - backend
  db:
    hostname: db
    image: mysql:5.7
    container_name: dbdaw
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
      - PMA_HOST=db
      - VIRTUAL_HOST=phpmyadmin.docker
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend:
    